# This is a basic workflow to help you run Repocket via Docker

name: Repocket Runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "repocket"
  repocket:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Installs Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker

      # Runs Repocket container using secrets
      - name: Run Repocket Docker container
        run: |
          docker run -d \
            --name repocket \
            --restart=always \
            -e RP_EMAIL="${{ secrets.REPOCKET_EMAIL }}" \
            -e RP_API_KEY="${{ secrets.REPOCKET_API_KEY }}" \
            repocket/repocket

      # Wait and display container logs
      - name: Wait and show logs
        run: |
          sleep 15
          docker logs repocket
