# This is a basic workflow to help you run Repocket via Docker

name: Repocket Runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  repocket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker (official script)
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Run Repocket Docker container
        run: |
          docker run -d \
            --name repocket \
            --restart=always \
            -e RP_EMAIL="${{ secrets.REPOCKET_EMAIL }}" \
            -e RP_API_KEY="${{ secrets.REPOCKET_API_KEY }}" \
            repocket/repocket

      - name: Wait and show logs
        run: |
          sleep 15
          docker logs repocket

      # Wait and display container logs
      - name: Wait and show logs
        run: |
          sleep 15
          docker logs repocket
